### PR TITLE
Update notification.rb

### PR DESCRIPTION
**Pull request by ab320012**

### CODE REVIEW

**Comment by ab320012** [comment]
#168 opening pr as i need the header in one of the apps i support

**Comment by dankimio** [comment]
Can you link the corresponding documentation?

**Comment by ab320012** [comment]
@dankimio hey yes, to be honest i don't think this PR actually modifies the header i am sort of confused as to how to encode that header with whats currently there do you mind helping?

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

Screen Shot 2019-09-24 at 3 52 25 PM

**Comment by dankimio** [comment]
@ab320012 Headers are a bit different from the payload.

**Comment by ab320012** [comment]
@dankimio yes i am aware wondering how i can get it done or if you are going to do add the header as it will break houston for ios13 which is already out

**Comment by nightpool** [comment]
It looks like Houston currently uses the legacy, binary notification format instead of the HTTP/2 api. Apple so far has not provided any documentation on how to supply this parameter with the legacy notification, or if one is even required. Has someone been able to test that pushes through Houston are actually rejected from an iOS 13 device, or are we just going off of possibly inaccurate documentation?

**Comment by khiav223577** [comment]
> @dankimio yes, to be honest i don't think this PR actually modifies the header i am sort of confused as to how to encode that header with whats currently there do you mind helping?
> 
> https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
> 
> Screen Shot 2019-09-24 at 3 52 25 PM

The documentation seems to have changed.
image

**Pull request closed without merging**
