### PR TITLE
Aa 139

### PR DESCRIPTION
**Pull request by andrewarrow**
for https://github.com/nomad/houston/issues/139

working with these env vars

```
export APN_PRIVATE_KEY=/Users/aa/dev/houston/APNsAuthKey_ABCDE12345.p8 
export APN_TEAM_ID=YOURTEAMID
export APN_KEY_ID=ABCDE12345
export APN_TOPIC=com.bundle.id
```

### CODE REVIEW

**Comment by JanC** [comment]
what is currently missing in the implementation to accept this PR?

**Comment by andrewarrow** [comment]
I made a new gem here with just the p8 format https://github.com/andrewarrow/p8push

this PR needs some work to make the p8 format work side by side with pem format.

**Comment by JanC** [comment]
alright, thanks

**Comment by RamblinWreck77** [comment]
Any reason this didn't get merged? It seems like .p8 is way better, having to refresh certs yearly is a PITA.

**Comment by andrewarrow** [comment]
Right on @RamblinWreck77 no reason not to merge IMO.

**Comment by RamblinWreck77** [comment]
@dankimio Any elaboration on why this was closed? Would really like this feature

**Comment by kristophM** [comment]
Curious why this was closed? p8 seems far superior

**Comment by andrewarrow** [comment]
I think the issue is OG houston without an p8 has tons of logic in it for the old system and it’s hard to make houston code base compatible for both options. Perhaps a new fork of houston called something like `houston-p8` with support only for p8 format is what is needed?

**Pull request closed without merging**
